// export enum ProviderErrorCode {
//   PROVIDER_ERROR = "PROVIDER_ERROR",

//   PROVIDER_NOT_FOUND = "PROVIDER_NOT_FOUND",
//   PROVIDER_ALREADY_REGISTERED = "PROVIDER_ALREADY_REGISTERED",
//   PROVIDER_REGISTRY_ERROR = "PROVIDER_REGISTRY_ERROR",

//   PROVIDER_RESOLUTION_ERROR = "PROVIDER_RESOLUTION_ERROR",

//   PROVIDER_FACTORY_ERROR = "PROVIDER_FACTORY_ERROR",

//   PROVIDER_CONFIGURATION_ERROR = "PROVIDER_CONFIGURATION_ERROR",

//   PROVIDER_VALIDATION_ERROR = "PROVIDER_VALIDATION_ERROR",

//   PROVIDER_CAPABILITY_NOT_SUPPORTED = "PROVIDER_CAPABILITY_NOT_SUPPORTED",

//   PROVIDER_LIFECYCLE_ERROR = "PROVIDER_LIFECYCLE_ERROR",

//   PROVIDER_INITIALIZATION_ERROR = "PROVIDER_INITIALIZATION_ERROR",

//   PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE",

//   PROVIDER_DISABLED = "PROVIDER_DISABLED",

//   PROVIDER_OPERATION_FAILED = "PROVIDER_OPERATION_FAILED",
// }

export enum ProviderErrorCode {
  PROVIDER_ERROR = "PROVIDER_ERROR",

  PROVIDER_NOT_FOUND = "PROVIDER_NOT_FOUND",

  PROVIDER_ALREADY_REGISTERED = "PROVIDER_ALREADY_REGISTERED",

  PROVIDER_REGISTRY_ERROR = "PROVIDER_REGISTRY_ERROR",

  PROVIDER_RESOLUTION_ERROR = "PROVIDER_RESOLUTION_ERROR",

  PROVIDER_FACTORY_ERROR = "PROVIDER_FACTORY_ERROR",

  PROVIDER_CONFIGURATION_ERROR = "PROVIDER_CONFIGURATION_ERROR",

  PROVIDER_VALIDATION_ERROR = "PROVIDER_VALIDATION_ERROR",

  PROVIDER_CAPABILITY_NOT_SUPPORTED = "PROVIDER_CAPABILITY_NOT_SUPPORTED",

  PROVIDER_LIFECYCLE_ERROR = "PROVIDER_LIFECYCLE_ERROR",

  PROVIDER_INITIALIZATION_ERROR = "PROVIDER_INITIALIZATION_ERROR",

  PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE",

  PROVIDER_DISABLED = "PROVIDER_DISABLED",

  PROVIDER_OPERATION_FAILED = "PROVIDER_OPERATION_FAILED",
}
