export enum DataClassification {
  PUBLIC = "PUBLIC",
  INTERNAL = "INTERNAL",
  CONFIDENTIAL = "CONFIDENTIAL",
  SENSITIVE = "SENSITIVE",
  HIGHLY_SENSITIVE = "HIGHLY_SENSITIVE",
  SECRET = "SECRET",
}
