export const APPLICATION_ID_PREFIX = "app";

export const APPLICATION_CODE_PREFIX = "APP";

export const APPLICATION_NAME_MAX_LENGTH = 150;

export const APPLICATION_SLUG_MAX_LENGTH = 150;

export const APPLICATION_CODE_MAX_LENGTH = 50;

export const APPLICATION_DESCRIPTION_MAX_LENGTH = 1000;
