export const ORGANIZATION_ID_PREFIX = "org";

export const ORGANIZATION_CODE_PREFIX = "ORG";

export const ORGANIZATION_NAME_MAX_LENGTH = 150;

export const ORGANIZATION_SLUG_MAX_LENGTH = 150;

export const ORGANIZATION_CODE_MAX_LENGTH = 50;

export const DEFAULT_ORGANIZATION_TIMEZONE = "UTC";
